<a href="https://colab.research.google.com/github/meetraval2006/Cricket-Shot-Predictor/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## pytorch fundamentals

In [ ]:
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
## Introduction to Tensors

#scalar:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[2,5,6],[3,6,9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 5, 6],
         [3, 6, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
WHAT = torch.tensor([[[[1,2,3,5],
                        [2,4,6,7],
                        [3,4,5,6]]]])
WHAT

tensor([[[[1, 2, 3, 5],
          [2, 4, 6, 7],
          [3, 4, 5, 6]]]])

In [ ]:
WHAT.ndim

4

In [ ]:
WHAT.shape

torch.Size([1, 1, 3, 4])

In [ ]:
 ### Random tensors: creating one of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.4300, 0.7898, 0.3245, 0.6689],
        [0.0942, 0.3312, 0.7001, 0.6351],
        [0.1088, 0.3489, 0.8821, 0.7037]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels(R, G, B).
random_image_size_tensor

tensor([[[0.1536, 0.5732, 0.9414],
         [0.4725, 0.6252, 0.8774],
         [0.9733, 0.3162, 0.6301],
         ...,
         [0.6751, 0.7867, 0.3252],
         [0.8212, 0.9900, 0.0226],
         [0.8136, 0.8495, 0.9902]],

        [[0.7856, 0.0630, 0.3262],
         [0.9699, 0.0080, 0.8354],
         [0.4769, 0.6492, 0.5934],
         ...,
         [0.2695, 0.7258, 0.0168],
         [0.1558, 0.9491, 0.8981],
         [0.1179, 0.1226, 0.4530]],

        [[0.4532, 0.6005, 0.6606],
         [0.1042, 0.9184, 0.3769],
         [0.9341, 0.8067, 0.6424],
         ...,
         [0.1091, 0.2583, 0.8426],
         [0.1045, 0.1066, 0.4580],
         [0.4665, 0.4379, 0.8061]],

        ...,

        [[0.8273, 0.6074, 0.8375],
         [0.4440, 0.6588, 0.9657],
         [0.0682, 0.2388, 0.6384],
         ...,
         [0.4762, 0.1402, 0.1361],
         [0.9017, 0.9154, 0.1753],
         [0.4501, 0.1061, 0.7338]],

        [[0.6976, 0.4414, 0.2185],
         [0.9820, 0.2126, 0.1175],
         [0.

In [ ]:
##Zeroes and ones
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## creating a range of tensors and tensors-like
#Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### Tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, #
                               requires_grad=False)#Wheather or not to trakc gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B)#Torch.mm is the same as torch.matmul. Writes less code


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#to fix the tensor shpae issues, we can manipulate the shape of one of our tensors using transpose
#A transpose switches the axes or dimensions of a tensor
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
#Finding the min, max, mean, sum, etc(tensor aggregation)
#use x.min/x.max to ge tthe min and amx values.

#to find the mean use
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#note:torch.mean function reqires a tensor of float32 datatype to work.
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
#fiind the sum:
x.sum()

tensor(450)

In [ ]:
r = torch.randn(4,4)
r


tensor([[ 0.3624, -0.0402,  1.0577, -0.9016],
        [-0.3109, -0.1379,  0.0311, -0.3723],
        [-0.0355, -0.0101,  1.8735,  0.2446],
        [ 0.8640,  0.5690, -1.0996, -1.5559]])

In [ ]:
torch.argmax(r, dim=1)

tensor([2, 2, 2, 0])

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
#Reshaping, stacking, squeezing, and unsqueezing tensors
#Reshaping - reshapes an input tensor to a defined shape
#View - Return a viewe of an an input tensor of a certain shape but keep the same memory as the original tensor.
#Stacking - Combine multiple tensors on top of each other(vstack) or (hstack)
#Squeeze = removes all 'l' dimensions frmo a tensor while unqueee adds a 1 dimension.
#permite - Return a view of the input with dimensions permuted(swapped) in a certain way.



In [ ]:
import torch
y = torch.arange(1.,10)
y, y.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
y_reshaped = y.reshape(1,9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [40]:
z = y.view(3,3)
z,y

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [51]:
#stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=2)
y_stacked

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]],

        [[4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.]],

        [[7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]])

In [54]:
# torch.squeeze removes all single dimensions
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
y_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
y_reshaped.squeeze().shape

torch.Size([9])